[project]
name = 'marketplace'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.DigitalRentals]
path = 'contracts/DigitalRentals.clar'
clarity_version = 3
epoch = 3.1

[contracts.Marketplace]
path = 'contracts/Marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.AssetWarranty]
path = 'contracts/AssetWarranty.clar'
clarity_version = 3
epoch = 3.1

[contracts.DisputeResolution]
path = 'contracts/DisputeResolution.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
